server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/neteasemusic?characterEnconding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=false
    username: root
    password: 123456

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml